# compose file for overriding general docker-compose.yml for development purpose
version: '2'
services:
  backend:
    restart: always
    build: ./MoJoFy
    image: mojofy_backend
    ports:
      - "3000:3000"
    depends_on:
          - datastore
    links:
      - datastore:datastore
    volumes_from:
      - local_cloud_storage_data
    environment:
      - BACKEND_WINSTON_LOG_LEVEL=debug
      - NODE_ENV=development
      - DEBUG=express:*
      - FRONTEND_URL=http://${DOCKER_MACHINE_IP}:8080
      - BACKEND_CLOUD_STORAGE_TYPE=local_cloud
      - LOCAL_CLOUD_STORAGE_HOST=http://${DOCKER_MACHINE_IP}
      - DATASTORE_EMULATOR_HOST=http://datastore:8081
      - BACKEND_DATASTORE_NAMESPACE=VIMOJO_DEV
      - BACKEND_GOOGLE_CLOUD_PROJECT_ID=videona-test
#      - BACKEND_EMAIL_NOTIFICATIONS_RECEIVER=${EMAIL_NOTIFICATIONS_RECEIVER}
#      - BACKEND_EMAIL_NOTIFICATIONS_SENDER=${EMAIL_NOTIFICATIONS_SENDER}
#      - SENDGRID_API_KEY
    env_file: .env_backend.ovr
    command: npm start
#    command: node -e 'console.log(process.env);'

  local_cloud_storage:
    restart: always
    build: ./local_cloud_storage/
    ports:
      - "80:80"
    volumes_from:
      - local_cloud_storage_data:ro
    links:
      - backend:backend

  local_cloud_storage_data:
    build: ./local_cloud_storage/
    volumes:
      - /app/uploads
    command: "true"

  frontend:
    restart: always
    build: ./platform-frontend
    image: mojofy_frontend
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - BACKEND_API_URL=http://${DOCKER_MACHINE_IP}:3000
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=8080
#    env_file: .env_frontend.dev
    command: npm start

  datastore:
    restart: always
    image: singularities/datastore-emulator
    environment:
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
      - DATASTORE_PROJECT_ID=videona-test
    volumes_from:
      - datastore-data
    expose:
      - 8081

  datastore-data:
    image: singularities/datastore-emulator
    volumes:
      - /opt/data
    command: "true"
