version: '2'
services:
  backend:
    restart: always
    build: ./MoJoFy
    image: mojofy_backend:${BACKEND_TAG}
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    environment:
      - NODE_ENV=production
      - MAX_VIDEO_UPLOAD_BYTE_SIZE=1500000
      - MAX_PROFILE_UPLOAD_BYTE_SIZE=1500000
      - BACKEND_WINSTON_LOG_LEVEL=info
      - ELASTIC_INDEX=test
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
      - ELASTIC_LOG=debug
#      - DB_TABLE_PREFIX=setup_table_prefix
#      - BACKEND_PERSISTENT_DB
#      - BACKEND_CLOUD_STORAGE_TYPE
#      - PORT
#      - JWT_SECRET
#      - JWT_ISSUER
#      - JWT_TOKEN_EXPIRATION
#      - SENDGRID_API_KEY
#      - BACKEND_EMAIL_NOTIFICATIONS_RECEIVER
#      - BACKEND_EMAIL_NOTIFICATIONS_SENDER
#      - BACKEND_DATASTORE_NAMESPACE
#      - BACKEND_GOOGLE_CLOUD_PROJECT_ID
#      - BACKEND_GCLOUD_STORAGE_ACCESS_ID
#      - BACKEND_GCLOUD_STORAGE_BUCKET
#      - AWS_KEY
#      - AWS_SECRET
#      - AWS_REGION
#      - ELASTIC_USER
#      - ELASTIC_PASS
#      - FLAVOUR
#      - AWS_ACCESS_KEY
#      - STORAGE_ACCESS_ID
#      - STORAGE_BUCKET
#      - STORAGE_KEY
# Auth0 config
#      - JWT_ISSUER
#      - AUTH0_AUDIENCE
#      - AUTH0_METADATA_NS
#      - AUTH0_BASE_URI

    env_file: .env_backend.prod
    command: npm start

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
    mem_limit: 2g
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1000m -Xmx1000m" # TODO: check appropiate limmits here
#    env_file: .env_elastic.prod


  frontend: # TODO: in production mode, we'll want just to build frontend and serve files using nginx or similar
    restart: always
    build:
      context: ./platform-frontend
      args:
        - NODE_ENV=production
        - BACKEND_API_URL=https://${DOCKER_MACHINE_IP}/api/v1
        - FRONTEND_HOST=0.0.0.0
        - FRONTEND_PORT=8080
        - MAX_VIDEO_UPLOAD_BYTE_SIZE=1500000
        - GMAPS_API_KEY=GmapsapiKey
        - FLAVOUR
        # Auth0
#        - AUTH0_CLIENT_ID
#        - AUTH0_DOMAIN
#        - AUTH0_AUDIENCE
#        - AUTH0_REDIRECT_URI
#        - AUTH0_SCOPE
#        - AUTH0_METADATA_NS

    image: mojofy_frontend:${FRONTEND_TAG}
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - BACKEND_API_URL=https://${DOCKER_MACHINE_IP}/api/v1
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=8080
      - MAX_VIDEO_UPLOAD_BYTE_SIZE=1500000
      - FLAVOUR
        # Auth0
#      - AUTH0_CLIENT_ID
#      - AUTH0_DOMAIN
#      - AUTH0_AUDIENCE
#      - AUTH0_REDIRECT_URI
#      - AUTH0_SCOPE
#      - AUTH0_METADATA_NS
#    env_file: .env_frontend.prod
    command: npm start

  front_proxy:
    restart: always
    build: ./front-proxy/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
      - video-uploads:/app/uploads

volumes:
  esdata1:
    driver: local
  certs:
    driver: local
  certs-data:
    driver: local
  video-uploads:
    driver: local
