version: '2'
services:
  backend:
    environment:
      - NODE_ENV=production
      - BACKEND_WINSTON_LOG_LEVEL=info
      - ELASTIC_INDEX=test
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
      - ELASTIC_LOG=debug
      - ELASTIC_USER=elastic
      - ELASTIC_PASS=changeme
      - PORT=3000
      - JWT_SECRET=Pr0d=s3crE7!
      - JWT_ISSUER=vimojo
      - JWT_TOKEN_EXPIRATION=1y
      - SENDGRID_API_KEY=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
      - BACKEND_EMAIL_NOTIFICATIONS_RECEIVER=jliarte@videona.com
      - BACKEND_EMAIL_NOTIFICATIONS_SENDER=info@videona.com
      - BACKEND_DATASTORE_NAMESPACE=VIMOJO_DEV
      - BACKEND_GOOGLE_CLOUD_PROJECT_ID=videona-test
#      - BACKEND_GCLOUD_STORAGE_ACCESS_ID
#      - BACKEND_GCLOUD_STORAGE_BUCKET
      - FLAVOUR=vimojo
      # - STORAGE_KEY=./flavour/vimojo/cloud-storage-key.pem
      # - STORAGE_ACCESS_ID=bigboss@vimojo-186017.iam.gserviceaccount.com
      - AWS_ACCESS_KEY=AKIAIMNHKSCZ3AVWM2BQ
      - AWS_SECRET=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
      - AWS_REGION=us-east-1
      - CDN_PATH=d2ggm04h8ck89b.cloudfront.net
      - BACKEND_PERSISTENT_DB=dynamo
      - BACKEND_SEARCH_DB=elasticsearch
      - DB_TABLE_PREFIX=vimojo_beta_
      - BACKEND_CLOUD_STORAGE_TYPE=aws
      - STORAGE_BUCKET=vimojo.beta.files

  frontend:
    build:
      context: ./platform-frontend
      args:
        - NODE_ENV=development
        - BACKEND_API_URL=https://beta.viday.co/api/v1
        - FRONTEND_HOST=0.0.0.0
        - FRONTEND_PORT=8080
        - FLAVOUR=vimojo
        - GMAPS_API_KEY=AIzaSyCSyWF1Lp-qYqQ9lgFEOxV7-5aQq-wfPGY
    environment:
      - NODE_ENV=development
      - BACKEND_API_URL=https://beta.viday.co/api/v1
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=8080
      - FLAVOUR=vimojo
      - GMAPS_API_KEY=AIzaSyCSyWF1Lp-qYqQ9lgFEOxV7-5aQq-wfPGY
